/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/ducati.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/ducati.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.SM_Engine_0000006.geometry} material={materials['MAT_Details_Engine.016']} rotation={[Math.PI / 2, 0, 0]} />
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.SM_Swingarm_0000001_1.geometry} material={materials['MAT_Tire_Brake.481']} />
        <mesh geometry={nodes.SM_Swingarm_0000001_2.geometry} material={materials['MAT_Details_EXT.504']} />
        <mesh geometry={nodes.SM_Swingarm_0000001_3.geometry} material={materials['MAT_Details_Add_01.033']} />
        <mesh geometry={nodes.SM_Swingarm_0000001_4.geometry} material={materials['MAT_Details_MAT.903']} />
      </group>
      <mesh geometry={nodes.SM_Disk_F_0000001.geometry} material={materials['MAT_Alpha_01.024']} position={[0.762, 0.189, -0.001]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.SM_Disk_R_0000017.geometry} material={materials['MAT_Alpha_01.028']} position={[-0.734, 0.226, -0.006]} rotation={[Math.PI / 2, 0, 0]} />
      <group position={[0.762, 0.189, -0.001]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.SM_Tire_F_0000001_1.geometry} material={materials['MAT_Tires_Tyre_F.005']} />
        <mesh geometry={nodes.SM_Tire_F_0000001_2.geometry} material={materials['MAT_Tires_Hub.032']} />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.SM_RearKit_0000016_1.geometry} material={materials['MAT_Details_MAT.898']} />
        <mesh geometry={nodes.SM_RearKit_0000016_2.geometry} material={materials['MAT_Details_Seat.005']} />
        <mesh geometry={nodes.SM_RearKit_0000016_3.geometry} material={materials['MAT_Lights.490']} />
        <mesh geometry={nodes.SM_RearKit_0000016_4.geometry} material={materials['MAT_Glass.415']} />
      </group>
      <mesh geometry={nodes.SM_Root_Ducati_StreetFighter_V4S_2024001.geometry} material={materials['MAT_Ducati_StreetFighter_V4S_Carpaint.008']} rotation={[Math.PI / 2, 0, 0]} />
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.SM_Fender_F_0000001_1.geometry} material={materials['MAT_Details_MAT.873']} />
        <mesh geometry={nodes.SM_Fender_F_0000001_2.geometry} material={materials['MAT_Details_EXT.486']} />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.SM_FrontKit_0000017_1.geometry} material={materials['MAT_Ducati_StreetFighter_V4S_Carpaint_Red.028']} />
        <mesh geometry={nodes.SM_FrontKit_0000017_2.geometry} material={materials['MAT_Details_EXT.499']} />
        <mesh geometry={nodes.SM_FrontKit_0000017_3.geometry} material={materials['MAT_Details_MAT.893']} />
        <mesh geometry={nodes.SM_FrontKit_0000017_4.geometry} material={materials['MAT_Lights.484']} />
        <mesh geometry={nodes.SM_FrontKit_0000017_5.geometry} material={materials['MAT_Glass.411']} />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.SM_Fork_0000001_1.geometry} material={materials['MAT_Glass.403']} />
        <mesh geometry={nodes.SM_Fork_0000001_2.geometry} material={materials['MAT_Lights.472']} />
        <mesh geometry={nodes.SM_Fork_0000001_3.geometry} material={materials['MAT_Tire_Brake.476']} />
        <mesh geometry={nodes.SM_Fork_0000001_4.geometry} material={materials['MAT_Details_EXT.489']} />
        <mesh geometry={nodes.SM_Fork_0000001_5.geometry} material={materials['MAT_Details_MAT.883']} />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.SM_Frame_0000001_1.geometry} material={materials['MAT_Details_Add_01.028']} />
        <mesh geometry={nodes.SM_Frame_0000001_2.geometry} material={materials['MAT_Details_Grid_01.248']} />
        <mesh geometry={nodes.SM_Frame_0000001_3.geometry} material={materials['MAT_Details_MAT.888']} />
        <mesh geometry={nodes.SM_Frame_0000001_4.geometry} material={materials['MAT_Glass.407']} />
        <mesh geometry={nodes.SM_Frame_0000001_5.geometry} material={materials['MAT_Lights.478']} />
        <mesh geometry={nodes.SM_Frame_0000001_6.geometry} material={materials['MAT_Ducati_StreetFighter_V4S_Carpaint_Red.018']} />
        <mesh geometry={nodes.SM_Frame_0000001_7.geometry} material={materials['MAT_Details_EXT.494']} />
      </group>
      <mesh geometry={nodes.SM_Fender_R_0000001.geometry} material={materials['MAT_Details_MAT.878']} rotation={[Math.PI / 2, 0, 0]} />
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.SM_Base_0000017_1.geometry} material={materials['MAT_Details_EXT.481']} />
        <mesh geometry={nodes.SM_Base_0000017_2.geometry} material={materials['MAT_Details_Grid_01.243']} />
        <mesh geometry={nodes.SM_Base_0000017_3.geometry} material={materials.MAT_Ducati_StreetFighter_V4S_Carpaint_Red} />
        <mesh geometry={nodes.SM_Base_0000017_4.geometry} material={materials['MAT_Details_MAT.868']} />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.SM_Exhaust_0000001_1.geometry} material={materials['MAT_Details_Engine.021']} />
        <mesh geometry={nodes.SM_Exhaust_0000001_2.geometry} material={materials['MAT_Details_Exhaust.005']} />
      </group>
      <group position={[-0.734, 0.226, -0.003]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.SM_Tire_R_0000001_1.geometry} material={materials['MAT_Tires_Tyre_R.005']} />
        <mesh geometry={nodes.SM_Tire_R_0000001_2.geometry} material={materials['MAT_Tires_Hub.037']} />
      </group>
    </group>
  )
}

useGLTF.preload('/ducati.glb')
